### ISSUE TITLE
Gramaire anglaise

### ISSUE THREAD

**Issue by Gwe2B** [JF-GIAMMARI/Conception_POO#4]
~~more high~~ than
**higher** than
https://github.com/JF-GIAMMARI/Conception_POO/blob/dd83b69a263b79cb435b4678d5842eb42d812a98/Exercices/src/forme/Bases/Forme.java#L40

**Comment by Gwe2B** [comment]
Oui je chipote pour des conneries mais me fait chier aussi essaie de me comprendre stp

**Comment by JF-GIAMMARI** [comment]
Mes stats github batard x)
